### ISSUE TITLE
EasyCaching

### ISSUE THREAD

**Issue by ianpowell2017** [buildasign/nop-hybrid-cache#1]
I am trying to follow your instructions to build my own version of EasyCache.

I understand you don't own the EasyCache repository but do you think you could provide more instruction on the changes made?  Perhaps a link to a fork of the repo where the changes have already been made?  That would be immensely useful.

**Comment by fendric** [comment]
I'm afraid all those changes were made in copy of the HybridCache repo that is not open to the public.
In the future we can work with the EasyCaching team to create a fork that is public, but right now we just don't have the bandwidth.
In any case, I wouldn't suggest attempting these changes until you have tested your load.
A lot of this was very specific to the object model choices we made in NOP that are very unique and custom to our business. You may not experience what we experienced.
Test your load with the regular libraries first to see if you run into any issues.

Having said that, to make things easy, I've added the changes we made into an EasyCaching folder in this repo.
You can copy these over your own copy of EasyCaching in order to create your own custom version.
